<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\Chat;
use CuadraAiLib\Models\ContentEx;

/**
 * Builder for model Chat
 *
 * @see Chat
 */
class ChatBuilder
{
    /**
     * @var Chat
     */
    private $instance;

    private function __construct(Chat $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Chat Builder object.
     *
     * @param string $model
     * @param ContentEx[] $content
     */
    public static function init(string $model, array $content): self
    {
        return new self(new Chat($model, $content));
    }

    /**
     * Sets chat Id field.
     *
     * @param string|null $value
     */
    public function chatId(?string $value): self
    {
        $this->instance->setChatId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Chat object.
     */
    public function build(): Chat
    {
        return CoreHelper::clone($this->instance);
    }
}
