<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\ContentEx;
use CuadraAiLib\Models\InlineDataEx;

/**
 * Builder for model ContentEx
 *
 * @see ContentEx
 */
class ContentExBuilder
{
    /**
     * @var ContentEx
     */
    private $instance;

    private function __construct(ContentEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Content Ex Builder object.
     *
     * @param string $text
     */
    public static function init(string $text): self
    {
        return new self(new ContentEx($text));
    }

    /**
     * Sets inline Data field.
     *
     * @param InlineDataEx|null $value
     */
    public function inlineData(?InlineDataEx $value): self
    {
        $this->instance->setInlineData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Content Ex object.
     */
    public function build(): ContentEx
    {
        return CoreHelper::clone($this->instance);
    }
}
