<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\EmbedResponseEx;
use CuadraAiLib\Models\UsageEx;

/**
 * Builder for model EmbedResponseEx
 *
 * @see EmbedResponseEx
 */
class EmbedResponseExBuilder
{
    /**
     * @var EmbedResponseEx
     */
    private $instance;

    private function __construct(EmbedResponseEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Embed Response Ex Builder object.
     */
    public static function init(): self
    {
        return new self(new EmbedResponseEx());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets usage field.
     *
     * @param UsageEx|null $value
     */
    public function usage(?UsageEx $value): self
    {
        $this->instance->setUsage($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Embed Response Ex object.
     */
    public function build(): EmbedResponseEx
    {
        return CoreHelper::clone($this->instance);
    }
}
