<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\InlineDataEx;

/**
 * Builder for model InlineDataEx
 *
 * @see InlineDataEx
 */
class InlineDataExBuilder
{
    /**
     * @var InlineDataEx
     */
    private $instance;

    private function __construct(InlineDataEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Inline Data Ex Builder object.
     */
    public static function init(): self
    {
        return new self(new InlineDataEx());
    }

    /**
     * Sets mime Type field.
     *
     * @param string|null $value
     */
    public function mimeType(?string $value): self
    {
        $this->instance->setMimeType($value);
        return $this;
    }

    /**
     * Sets data field.
     *
     * @param string|null $value
     */
    public function data(?string $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Inline Data Ex object.
     */
    public function build(): InlineDataEx
    {
        return CoreHelper::clone($this->instance);
    }
}
