<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\ModelEx;
use CuadraAiLib\Models\PaginatedResponseExListModelEx;

/**
 * Builder for model PaginatedResponseExListModelEx
 *
 * @see PaginatedResponseExListModelEx
 */
class PaginatedResponseExListModelExBuilder
{
    /**
     * @var PaginatedResponseExListModelEx
     */
    private $instance;

    private function __construct(PaginatedResponseExListModelEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paginated Response Ex List Model Ex Builder object.
     */
    public static function init(): self
    {
        return new self(new PaginatedResponseExListModelEx());
    }

    /**
     * Sets page field.
     *
     * @param int|null $value
     */
    public function page(?int $value): self
    {
        $this->instance->setPage($value);
        return $this;
    }

    /**
     * Sets size field.
     *
     * @param int|null $value
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Sets data field.
     *
     * @param ModelEx[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Paginated Response Ex List Model Ex object.
     */
    public function build(): PaginatedResponseExListModelEx
    {
        return CoreHelper::clone($this->instance);
    }
}
