<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\TokensEx;

/**
 * Builder for model TokensEx
 *
 * @see TokensEx
 */
class TokensExBuilder
{
    /**
     * @var TokensEx
     */
    private $instance;

    private function __construct(TokensEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tokens Ex Builder object.
     */
    public static function init(): self
    {
        return new self(new TokensEx());
    }

    /**
     * Sets input Tokens field.
     *
     * @param int|null $value
     */
    public function inputTokens(?int $value): self
    {
        $this->instance->setInputTokens($value);
        return $this;
    }

    /**
     * Sets output Tokens field.
     *
     * @param int|null $value
     */
    public function outputTokens(?int $value): self
    {
        $this->instance->setOutputTokens($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Tokens Ex object.
     */
    public function build(): TokensEx
    {
        return CoreHelper::clone($this->instance);
    }
}
