<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\TotalUsageEx;

/**
 * Builder for model TotalUsageEx
 *
 * @see TotalUsageEx
 */
class TotalUsageExBuilder
{
    /**
     * @var TotalUsageEx
     */
    private $instance;

    private function __construct(TotalUsageEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Total Usage Ex Builder object.
     */
    public static function init(): self
    {
        return new self(new TotalUsageEx());
    }

    /**
     * Sets total Input field.
     *
     * @param int|null $value
     */
    public function totalInput(?int $value): self
    {
        $this->instance->setTotalInput($value);
        return $this;
    }

    /**
     * Sets total Output field.
     *
     * @param int|null $value
     */
    public function totalOutput(?int $value): self
    {
        $this->instance->setTotalOutput($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Total Usage Ex object.
     */
    public function build(): TotalUsageEx
    {
        return CoreHelper::clone($this->instance);
    }
}
