<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\TokensEx;
use CuadraAiLib\Models\UsageEx;

/**
 * Builder for model UsageEx
 *
 * @see UsageEx
 */
class UsageExBuilder
{
    /**
     * @var UsageEx
     */
    private $instance;

    private function __construct(UsageEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Usage Ex Builder object.
     */
    public static function init(): self
    {
        return new self(new UsageEx());
    }

    /**
     * Sets billed Tokens field.
     *
     * @param TokensEx|null $value
     */
    public function billedTokens(?TokensEx $value): self
    {
        $this->instance->setBilledTokens($value);
        return $this;
    }

    /**
     * Sets used Tokens field.
     *
     * @param TokensEx|null $value
     */
    public function usedTokens(?TokensEx $value): self
    {
        $this->instance->setUsedTokens($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Usage Ex object.
     */
    public function build(): UsageEx
    {
        return CoreHelper::clone($this->instance);
    }
}
