<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models\Builders;

use Core\Utils\CoreHelper;
use CuadraAiLib\Models\UsageCalculationEx;

/**
 * Builder for model UsageCalculationEx
 *
 * @see UsageCalculationEx
 */
class UsageCalculationExBuilder
{
    /**
     * @var UsageCalculationEx
     */
    private $instance;

    private function __construct(UsageCalculationEx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Usage Calculation Ex Builder object.
     */
    public static function init(): self
    {
        return new self(new UsageCalculationEx());
    }

    /**
     * Sets estimated Tokens field.
     *
     * @param int|null $value
     */
    public function estimatedTokens(?int $value): self
    {
        $this->instance->setEstimatedTokens($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Usage Calculation Ex object.
     */
    public function build(): UsageCalculationEx
    {
        return CoreHelper::clone($this->instance);
    }
}
