<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use CuadraAiLib\Exceptions\ErrorResponseException;
use CuadraAiLib\Http\ApiResponse;
use CuadraAiLib\Models\Chat;
use CuadraAiLib\Models\ChatResponseEx;

class ChatController extends BaseController
{
    /**
     * This endpoint creates a new chat interaction with our AI Models.
     *
     * @param Chat $body
     *
     * @return ApiResponse Response from the API call
     */
    public function chat(Chat $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/chat')
            ->auth('OAuth2')
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad request, read again our documentation or contact support for guidance.',
                    ErrorResponseException::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init('Not authorized, check our OAuth2 doc.', ErrorResponseException::class)
            )
            ->throwErrorOn(
                '500',
                ErrorType::init(
                    'Internal error, if this error persist, please contact support.',
                    ErrorResponseException::class
                )
            )
            ->type(ChatResponseEx::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
