<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models;

use CuadraAiLib\ApiHelper;
use stdClass;

/**
 * Request content
 */
class ContentEx implements \JsonSerializable
{
    /**
     * @var string
     */
    private $text;

    /**
     * @var InlineDataEx|null
     */
    private $inlineData;

    /**
     * @param string $text
     */
    public function __construct(string $text)
    {
        $this->text = $text;
    }

    /**
     * Returns Text.
     * Text is the task you want the AI to solve.
     */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     * Text is the task you want the AI to solve.
     *
     * @required
     * @maps text
     */
    public function setText(string $text): void
    {
        $this->text = $text;
    }

    /**
     * Returns Inline Data.
     * Input Reference is the name of the file, if you're request is from a type other than text, and it's
     * required for most types. It has to contain the same name as the file attached in the request.
     */
    public function getInlineData(): ?InlineDataEx
    {
        return $this->inlineData;
    }

    /**
     * Sets Inline Data.
     * Input Reference is the name of the file, if you're request is from a type other than text, and it's
     * required for most types. It has to contain the same name as the file attached in the request.
     *
     * @maps inlineData
     */
    public function setInlineData(?InlineDataEx $inlineData): void
    {
        $this->inlineData = $inlineData;
    }

    /**
     * Converts the ContentEx object to a human-readable string representation.
     *
     * @return string The string representation of the ContentEx object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ContentEx',
            [
                'text' => $this->text,
                'inlineData' => $this->inlineData,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['text', 'inlineData'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['text']           = $this->text;
        if (isset($this->inlineData)) {
            $json['inlineData'] = $this->inlineData;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
