<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models;

use CuadraAiLib\ApiHelper;
use stdClass;

class EmbedResponseEx implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var UsageEx|null
     */
    private $usage;

    /**
     * Returns Id.
     * Embed id
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Embed id
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Usage.
     * This is the token usage result of your request
     */
    public function getUsage(): ?UsageEx
    {
        return $this->usage;
    }

    /**
     * Sets Usage.
     * This is the token usage result of your request
     *
     * @maps usage
     */
    public function setUsage(?UsageEx $usage): void
    {
        $this->usage = $usage;
    }

    /**
     * Converts the EmbedResponseEx object to a human-readable string representation.
     *
     * @return string The string representation of the EmbedResponseEx object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EmbedResponseEx',
            ['id' => $this->id, 'usage' => $this->usage, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['id', 'usage'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']    = $this->id;
        }
        if (isset($this->usage)) {
            $json['usage'] = $this->usage;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
