<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models;

use CuadraAiLib\ApiHelper;
use stdClass;

/**
 * Input Reference is the name of the file, if you're request is from a type other than text, and it's
 * required for most types. It has to contain the same name as the file attached in the request.
 */
class InlineDataEx implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $mimeType;

    /**
     * @var string|null
     */
    private $data;

    /**
     * Returns Mime Type.
     */
    public function getMimeType(): ?string
    {
        return $this->mimeType;
    }

    /**
     * Sets Mime Type.
     *
     * @maps mimeType
     */
    public function setMimeType(?string $mimeType): void
    {
        $this->mimeType = $mimeType;
    }

    /**
     * Returns Data.
     */
    public function getData(): ?string
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @maps data
     */
    public function setData(?string $data): void
    {
        $this->data = $data;
    }

    /**
     * Converts the InlineDataEx object to a human-readable string representation.
     *
     * @return string The string representation of the InlineDataEx object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'InlineDataEx',
            [
                'mimeType' => $this->mimeType,
                'data' => $this->data,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['mimeType', 'data'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->mimeType)) {
            $json['mimeType'] = $this->mimeType;
        }
        if (isset($this->data)) {
            $json['data']     = $this->data;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
