<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib\Models;

use CuadraAiLib\ApiHelper;
use stdClass;

/**
 * This is the token usage result of your request
 */
class UsageEx implements \JsonSerializable
{
    /**
     * @var TokensEx|null
     */
    private $billedTokens;

    /**
     * @var TokensEx|null
     */
    private $usedTokens;

    /**
     * Returns Billed Tokens.
     * Tokens used
     */
    public function getBilledTokens(): ?TokensEx
    {
        return $this->billedTokens;
    }

    /**
     * Sets Billed Tokens.
     * Tokens used
     *
     * @maps billedTokens
     */
    public function setBilledTokens(?TokensEx $billedTokens): void
    {
        $this->billedTokens = $billedTokens;
    }

    /**
     * Returns Used Tokens.
     * Tokens used
     */
    public function getUsedTokens(): ?TokensEx
    {
        return $this->usedTokens;
    }

    /**
     * Sets Used Tokens.
     * Tokens used
     *
     * @maps usedTokens
     */
    public function setUsedTokens(?TokensEx $usedTokens): void
    {
        $this->usedTokens = $usedTokens;
    }

    /**
     * Converts the UsageEx object to a human-readable string representation.
     *
     * @return string The string representation of the UsageEx object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UsageEx',
            [
                'billedTokens' => $this->billedTokens,
                'usedTokens' => $this->usedTokens,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['billedTokens', 'usedTokens'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->billedTokens)) {
            $json['billedTokens'] = $this->billedTokens;
        }
        if (isset($this->usedTokens)) {
            $json['usedTokens']   = $this->usedTokens;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
