<?php

declare(strict_types=1);

/*
 * CuadraAiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CuadraAiLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Production Server
     */
    public const PRODUCTION = 'production';
}
